# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai_inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61i_inference.proto\x12\x0b\x61iinference\" \n\x10SentimentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"6\n\x11SentimentResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\"!\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"!\n\x10GenerateResponse\x12\r\n\x05token\x18\x01 \x01(\t\"\x19\n\tTextChunk\x12\x0c\n\x04text\x18\x01 \x01(\t\"\"\n\x0fSummaryResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\",\n\x0b\x43hatMessage\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb9\x02\n\x0b\x41IInference\x12Q\n\x10\x41nalyzeSentiment\x12\x1d.aiinference.SentimentRequest\x1a\x1e.aiinference.SentimentResponse\x12M\n\x0cGenerateText\x12\x1c.aiinference.GenerateRequest\x1a\x1d.aiinference.GenerateResponse0\x01\x12H\n\x0eSummarizeBatch\x12\x16.aiinference.TextChunk\x1a\x1c.aiinference.SummaryResponse(\x01\x12>\n\x04\x43hat\x12\x18.aiinference.ChatMessage\x1a\x18.aiinference.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENTIMENTREQUEST']._serialized_start=35
  _globals['_SENTIMENTREQUEST']._serialized_end=67
  _globals['_SENTIMENTRESPONSE']._serialized_start=69
  _globals['_SENTIMENTRESPONSE']._serialized_end=123
  _globals['_GENERATEREQUEST']._serialized_start=125
  _globals['_GENERATEREQUEST']._serialized_end=158
  _globals['_GENERATERESPONSE']._serialized_start=160
  _globals['_GENERATERESPONSE']._serialized_end=193
  _globals['_TEXTCHUNK']._serialized_start=195
  _globals['_TEXTCHUNK']._serialized_end=220
  _globals['_SUMMARYRESPONSE']._serialized_start=222
  _globals['_SUMMARYRESPONSE']._serialized_end=256
  _globals['_CHATMESSAGE']._serialized_start=258
  _globals['_CHATMESSAGE']._serialized_end=302
  _globals['_AIINFERENCE']._serialized_start=305
  _globals['_AIINFERENCE']._serialized_end=618
# @@protoc_insertion_point(module_scope)
