events {}

http {
    upstream ai_backend {
        server ai-server-1:50051;
        server ai-server-2:50051;
        server ai-server-3:50051;
    }

    server {
        listen 50051 http2;

        location / {
            grpc_pass grpc://ai_backend;
        }
    }
}